#Streaming_Tools_Streaming_Tools_AYzWTqKrts2n-SECBp_e
# Starter pipeline
# Starter pipeline
name: 1.0.2.$(rev:r)
variables: 
- name: Project.Path
  value: $(Build.SourcesDirectory)/**/LurkHelper.csproj 
# - name: Sonar.Key
#   value: Streaming_Tools_Streaming_Tools_AYzWTqKrts2n-SECBp_e
# - name: Sonar.Name
#   value: d867bde1-149e-487a-bb48-62bbf99de099
- name: BuildConfiguration
  value: Release
- name: Nuspec.ServiceId
  value: 015fc12f-cd63-4ab4-8d6a-dc889e53bf70
trigger:
  branches:
    include:
    - refs/heads/main
  paths:
    include:
    - src

jobs:
- job: Phase_1 
  cancelTimeoutInMinutes: 1
  pool:
    name: Default
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      projects: '$(Project.Path)'
      feedRestore: '$(Nuspec.ServiceId)'
  - task: DotNetCoreCLI@2
    displayName: dotnet build 
    inputs:
      projects: '$(Project.Path)'
      arguments: '--configuration Release --no-restore' 
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'Streaming Tools'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'gitTag'      
      tagPattern: 'release-v1.*'
      title: 'LurkeyTurkey'
      isPreRelease: true
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
 
  - task: SonarSource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@5
    displayName: Run Code Analysis
    enabled: false
    continueOnError: True
    inputs:
      jdkversion: JAVA_HOME
  - task: SonarSource.sonarqube.291ed61f-1ee4-45d3-b1b0-bf822d9095ef.SonarQubePublish@5
    displayName: Publish Quality Gate Result
    enabled: false
    continueOnError: True

