# Starter pipeline
name: 1.0.0.$(rev:r)

variables: 
- name: Project.Path
  value: '**/PolyhydraGames.Core.Console.csproj'
- name: Project.Config
  value: release
trigger:
  branches:
    include:
    - refs/heads/main
  paths:
    include:
    - src
jobs:
- job: Phase_1 
  cancelTimeoutInMinutes: 1
  
  pool:
    #vmImage: windows-latest
    name: Default 
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: $(Project.Path)
      feedRestore: 015fc12f-cd63-4ab4-8d6a-dc889e53bf70
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '$(Project.Path)'
      arguments:  --no-restore
      configuration: $(Project.Config) 
  - task: DotNetCoreCLI@2
    displayName: dotnet build and pack
    inputs:
      command: pack
      packagesToPack: '$(Project.Path)' 
      versioningScheme: 'byBuildNumber'
      arguments: --configuration $(Project.Config) --no-build
  - task: NuGetCommand@2
    displayName: Poly NuGet push
    inputs:
      command: push
      feedPublish: 015fc12f-cd63-4ab4-8d6a-dc889e53bf70
      allowPackageConflicts: false
  - task: NuGetCommand@2
    displayName: NuGet.org push
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'Nuget Org'
